@ECHO off
SET UP_KEY=1
SET LEFT_KEY=2
SET DOWN_KEY=3
SET RIGHT_KEY=4
SET QUIT_KEY=5
SET FASTER_KEY=6
SET SLOWER_KEY=7
SET INPUTKEY=NONE
SET DIRECTION=NONE
SET SPEED=7
DEL *.tmp > NUL 2>&1
ECHO 1 >running.tmp